import os
import json
import torch
import numpy as np
from PIL import Image

from model import SegformerB3Custom
from tta import tta_infer
from mc_dropout import mc_dropout_infer
from postprocess import apply_morphology

def run_inference(model, tile_tensor, uncertainty_mode="tta_variance"):
    """
    Runs inference using the chosen uncertainty mode.
    Returns:
        prob_map: (H, W) float
        uncertainty_map: (H, W) float
    """
    if uncertainty_mode == "tta_variance":
        print("Using TTA for fast uncertainty estimation...")
        prob_tensor, uncert_tensor = tta_infer(model, tile_tensor)
        
    elif uncertainty_mode == "mc_dropout":
        print("Using MC Dropout for deep epistemic uncertainty estimation...")
        prob_tensor, uncert_tensor = mc_dropout_infer(model, tile_tensor, n_samples=30)
        
    else: # "none"
        print("Standard single-pass inference...")
        model.eval()
        with torch.no_grad():
            logits = model(tile_tensor)
            if isinstance(logits, tuple):
                logits = logits[0]
            prob_tensor = torch.sigmoid(logits)
            uncert_tensor = torch.zeros_like(prob_tensor)
            
    prob_map = prob_tensor[0, 0].cpu().numpy()
    uncertainty_map = uncert_tensor[0, 0].cpu().numpy()
    return prob_map, uncertainty_map

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--tile", type=str, required=True, help="Path to input tile (or dummy)")
    parser.add_argument("--checkpoint", type=str, required=True, help="Path to trained model")
    parser.add_argument("--uncertainty-mode", type=str, choices=["mc_dropout", "tta_variance", "none"], default="tta_variance")
    parser.add_argument("--output-dir", type=str, default="outputs/final")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)
    
    # 1. Load Model (Mocked for local dev if weights are missing)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = SegformerB3Custom(in_channels=10, num_classes=1, backbone="segformer_b3")
    try:
        model.load_state_dict(torch.load(args.checkpoint, map_location=device))
        print(f"Loaded checkpoint from {args.checkpoint}")
    except Exception as e:
        print(f"Failed to load checkpoint (using untrained weights for local test). Error: {e}")
    model.to(device)
    
    # 2. Mock Tile Tensor (1, 10, 1024, 1024)
    # In a real run, this would be generated by fusion.py
    tile_tensor = torch.rand(1, 10, 1024, 1024).to(device)
    
    # 3. Inference with Uncertainty
    prob_map, uncertainty_map = run_inference(model, tile_tensor, args.uncertainty_mode)
    
    # 4. Binary Thresholding
    raw_mask = prob_map > 0.5
    
    # 5. Morphological Post-processing
    clean_mask = apply_morphology(raw_mask, uncertainty_map, uncertainty_threshold=0.3)
    
    # 6. Compute Metadata
    uncertain_mask = uncertainty_map > 0.3
    
    # Intersection of road pixels and uncertain pixels
    uncertain_road_pixels = (clean_mask & uncertain_mask).sum()
    total_road_pixels = clean_mask.sum()
    
    uncertain_fraction = 0.0
    if total_road_pixels > 0:
        uncertain_fraction = float(uncertain_road_pixels) / float(total_road_pixels)
        
    print(f"Uncertain Road Fraction: {uncertain_fraction:.2%}")
    
    # 7. Save Outputs for Part B (Pathfinding)
    road_path = os.path.join(args.output_dir, "road_mask.npy")
    uncert_path = os.path.join(args.output_dir, "uncertainty_mask.npy")
    meta_path = os.path.join(args.output_dir, "meta.json")
    
    np.save(road_path, clean_mask)
    np.save(uncert_path, uncertain_mask)
    
    meta = {
        "tile_id": os.path.basename(args.tile),
        "uncertainty_mode": args.uncertainty_mode,
        "uncertain_fraction": uncertain_fraction,
        "outputs": {
            "road_mask": road_path,
            "uncertainty_mask": uncert_path
        }
    }
    
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=4)
        
    print(f"Successfully generated final outputs in {args.output_dir}")

if __name__ == "__main__":
    main()
